export const CHECKOUT_REVALIDATION_SERVICE = Symbol('CHECKOUT_REVALIDATION_SERVICE');
export const CHECKOUT_ORDER_SERVICE = Symbol('CHECKOUT_ORDER_SERVICE');
export const PAYMENT_CONFIRMATION_SERVICE = Symbol('PAYMENT_CONFIRMATION_SERVICE');
