export const CASH_SESSION_REPOSITORY = Symbol('CASH_SESSION_REPOSITORY');
export const CASH_SESSION_SERVICE = Symbol('CASH_SESSION_SERVICE');
export const STAFF_PIN_REPOSITORY = Symbol('STAFF_PIN_REPOSITORY');
export const STAFF_PIN_SERVICE = Symbol('STAFF_PIN_SERVICE');
