export const SIGNUP_OTP_SERVICE = Symbol('SIGNUP_OTP_SERVICE');
export const SIGNUP_PROVISIONING_SERVICE = Symbol('SIGNUP_PROVISIONING_SERVICE');
export const SIGNUP_RATE_LIMITER = Symbol('SIGNUP_RATE_LIMITER');
