export const LOYALTY_CONFIG_SERVICE = Symbol('LOYALTY_CONFIG_SERVICE');
export const LOYALTY_BALANCE_REPOSITORY = Symbol('LOYALTY_BALANCE_REPOSITORY');
export const LOYALTY_CREDITOR = Symbol('LOYALTY_CREDITOR');
